services:
  sub-manager:
    build:
      context: .
    image: sub-manager:${SUB_MANAGER_VERSION:-3.4.4}
    container_name: sub-manager
    restart: unless-stopped
    ports:
      - "7777:7777"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data:/data
