[supervisord]
nodaemon=true
logfile=/data/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/data

[program:subconverter]
command=subconverter
directory=/base
autostart=true
autorestart=true
startsecs=1
stdout_logfile=/data/subconverter.log
stderr_logfile=/data/subconverter-error.log
stopasgroup=true
killasgroup=true

[program:submanager]
command=/opt/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 7777 --proxy-headers --forwarded-allow-ips=%(ENV_FORWARDED_ALLOW_IPS)s --no-access-log
directory=/app
environment=PYTHONUNBUFFERED="1"
autostart=true
autorestart=true
startsecs=1
stdout_logfile=/data/submanager.log
stderr_logfile=/data/submanager-error.log
stopasgroup=true
killasgroup=true

[group:sub-manager]
programs=subconverter,submanager
priority=999
