export interface Upstream { id?:number; name:string; url?:string; url_masked?:string; enabled:boolean; rename_policy:'inherit'|'smart'|'passthrough'|'disabled'; rename_ignore:string; rename_template:string; last_status?:string; last_http_status?:number; last_content_type?:string; last_bytes:number; last_duration_ms?:number; last_success_at?:string; last_error?:string; source_format?:string; node_count:number; filtered_count:number; used_cache:boolean }
export interface Output { id?:number; client_type:string; name:string; slug:string; update_interval_minutes:number; enabled:boolean }
export interface ManualNode {id:number;name:string;final_name?:string;protocol:string;node_key:string;enabled:boolean;sort_order:number;created_at:string;updated_at:string}
export interface Group { id:number; name:string; note:string; enabled:boolean; interval_minutes:number; rename_mode:'passthrough'|'smart'; rename_ignore:string; rename_template:string; ip_whitelist?:string; pending_node_count:number; last_refresh_status?:string; last_error?:string; last_attempt_at?:string; last_success_at?:string; next_refresh_at?:string; refresh_count:number; node_count:number; filtered_count:number; last_duration_ms?:number; cache_state:string; upstreams:Upstream[]; manual_nodes?:ManualNode[]; outputs:Output[] }
export interface Settings { site_name:string; public_base_url:string; admin_username:string; default_refresh_interval_minutes:number; default_output_interval_minutes:number; default_client_type:string; upstream_timeout_seconds:number; converter_timeout_seconds:number; pseudo_node_filter:string; scheduler_enabled:boolean; stale_cache_fallback:boolean; skip_failed_upstreams:boolean; upstream_user_agent:string; scheduler_concurrency:number; health_check_enabled:boolean; health_check_interval_minutes:number; health_check_concurrency:number; health_check_timeout_seconds:number; health_notify_enabled:boolean; health_notify_webhook:string; health_notify_threshold:number; default_credentials:boolean; listen_port:number; data_dir:string }
export interface ClientType { label:string; target:string; ext:string; rules:boolean; ver?:string }
export interface RefreshRun { id:number; subscription_id:number; subscription_name:string; trigger:'manual'|'scheduler'|'public'; status:string; started_at:string; finished_at:string; duration_ms:number; upstream_total:number; upstream_success:number; output_total:number; output_success:number; node_count:number; filtered_count:number; error?:string }
export interface NodeSnapshot { position:number; node_key:string; original_name:string; rule_name:string; alias?:string; final_name:string; source_name:string; protocol:string; confirmation_status:'confirmed'|'pending_new'|'pending_changed'; previous_name?:string; traffic:string; reset:string; updated_at:string; health_status?:string; connectivity_latency_ms?:number; google_ok?:boolean; google_latency_ms?:number; consecutive_failures?:number; health_tested_at?:string; error_code?:string }
export interface OutputStatus { id:number; name:string; slug:string; client_type:string; enabled:boolean; status:'ready'|'empty'; updated_at?:string; bytes:number; renderer?:string; skipped_nodes:number; node_count:number; url?:string }
