<script setup lang="ts">
import{computed,onMounted}from'vue';import{useRouter}from'vue-router';import{Activity,AlertTriangle,Layers3,Radio,RefreshCw,Server,Timer,Workflow}from'lucide-vue-next';import{useOverviewStore}from'../stores/overview';import{useAppStore}from'../stores/app';import StatusTag from'../components/StatusTag.vue';
const overview=useOverviewStore(),app=useAppStore(),router=useRouter();onMounted(async()=>{await Promise.all([overview.load(),app.bootstrap()])});const d=computed(()=>overview.data||{});const dt=(v?:string)=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'—';const duration=(v?:number)=>v==null?'—':v<1000?`${v} ms`:`${(v/1000).toFixed(1)} s`;
</script>
<template><section class="page overview-page"><header class="page-head"><div><p class="eyebrow">OPERATIONS CENTER</p><h1>运行概览</h1><p>先看异常，再处理需要关注的订阅组。</p></div><el-button :loading="overview.loading" @click="overview.load"><RefreshCw/>刷新状态</el-button></header>
<div v-if="app.settings?.default_credentials" class="security-alert danger"><AlertTriangle/><div><b>仍在使用默认管理员密码</b><span>请立即前往系统设置修改，避免上游地址泄露。</span></div><el-button @click="router.push('/settings')">立即修改</el-button></div>
<div class="stats overview-stats"><div class="stat"><span class="stat-icon blue"><Layers3/></span><div><b>{{d.groups_enabled||0}} / {{d.groups_total||0}}</b><span>启用订阅组</span></div></div><div class="stat"><span class="stat-icon green"><Server/></span><div><b>{{d.upstreams_healthy||0}} / {{d.upstreams_total||0}}</b><span>健康上游</span></div></div><div class="stat"><span class="stat-icon purple"><Radio/></span><div><b>{{d.node_health?.available||0}} / {{d.nodes_total||0}}</b><span>测活可用 / 有效节点</span></div></div><div class="stat"><span class="stat-icon amber"><AlertTriangle/></span><div><b>{{(d.status_counts?.partial||0)+(d.status_counts?.stale||0)+(d.status_counts?.error||0)+(d.pending_nodes||0)}}</b><span>异常组与待确认节点</span></div></div></div>
<div class="ops-grid"><section class="panel ops-panel"><header><div><h2>需要关注</h2><p>部分异常、旧缓存、失败组和待确认节点优先显示。</p></div><el-button link type="primary" @click="router.push('/groups')">查看全部</el-button></header><div v-if="d.attention_groups?.length" class="attention-list"><article v-for="g in d.attention_groups" :key="g.id" @click="router.push(`/groups/${g.id}/detail`)"><StatusTag :status="g.last_refresh_status"/><div><b>{{g.name}}</b><span>{{g.last_error||(g.pending_node_count?g.pending_node_count+' 个节点等待确认':'缓存状态需要检查')}}</span></div><small>{{g.node_count}} 节点</small></article></div><div v-else class="compact-empty"><Activity/><b>所有订阅组运行正常</b><span>当前没有需要立即处理的异常。</span></div></section>
<section class="panel ops-panel runtime-panel"><header><div><h2>调度器</h2><p>后台刷新与依赖服务实时状态。</p></div></header><div class="runtime-metrics"><div><span><Timer/>定时刷新</span><b :class="{good:app.health.scheduler_enabled}">{{app.health.scheduler_enabled?'已启用':'已关闭'}}</b></div><div><span><Workflow/>正在运行</span><b>{{app.health.active_refreshes||0}} 个任务</b></div><div><span><RefreshCw/>待刷新</span><b>{{app.health.due_groups||0}} 个组</b></div><div><span><Server/>转换器</span><b :class="{good:app.health.subconverter}">{{app.health.subconverter?'正常':'不可用'}}</b></div></div><p class="runtime-foot">最近轮询 {{dt(app.health.last_poll_at)}} · 下次 {{dt(app.health.next_poll_at)}}</p></section></div>
<section class="panel ops-panel recent-panel"><header><div><h2>最近运行</h2><p>刷新来源、耗时与结果。</p></div><el-button link type="primary" @click="router.push('/runs')">完整记录</el-button></header><el-table :data="d.recent_runs||[]" empty-text="暂无运行记录"><el-table-column prop="subscription_name" label="订阅组" min-width="180"/><el-table-column label="结果" width="110"><template #default="{row}"><StatusTag :status="row.status"/></template></el-table-column><el-table-column label="来源" width="100"><template #default="{row}">{{row.trigger==='manual'?'手动':row.trigger==='scheduler'?'定时':'公共请求'}}</template></el-table-column><el-table-column label="节点" width="90"><template #default="{row}">{{row.node_count}}</template></el-table-column><el-table-column label="耗时" width="100"><template #default="{row}">{{duration(row.duration_ms)}}</template></el-table-column><el-table-column label="完成时间" min-width="170"><template #default="{row}">{{dt(row.finished_at)}}</template></el-table-column></el-table></section></section></template>
